# data
dataset: 'kspon'
dataset_path: ''
transcripts_path: '../../../data/transcripts.txt'
output_unit: 'character'

# trainer
num_epochs: 1
batch_size: 32 #32
save_result_every: 100
checkpoint_every: 100
print_every: 10
mode: 'train'
seed: 777
resume: false

# device
num_workers: 4
use_cuda: True

# optim
optimizer: 'adam'
init_lr: 1e-07 #1e-06
final_lr: 1e-07 #1e-06
peak_lr: 1e-04 #1e-04
init_lr_scale: 0.01 #0.01s
final_lr_scale: 0.05 #0.05
max_grad_norm: 400 #400
warmup_steps: 400 #400
weight_decay: 1e-05 #1e-05
reduction: 'mean'